Давайте рассмотрим, как с помощью функций Python мы сможем применить квазиньютоновские методы для оптимизации функции

.

Подгрузим необходимые библиотеки:

In [2]:
import numpy as np
from scipy.optimize import minimize

Определим функцию, которую будем оптимизировать. Вместо отдельных и  можно взять координаты единого вектора:

In [3]:
def func(x):
    return x[0]**2.0 + x[1]**2.0

Теперь определим градиент для функции:

In [4]:
def grad_func(x):
    return np.array([x[0] * 2, x[1] * 2])

Зададим начальную точку:

In [5]:
x_0 = [1.0, 1.0]

Определим алгоритм:

In [6]:
result = minimize(func, x_0, method='BFGS', jac=grad_func)

Выведем результаты:

In [7]:
print('Статус оптимизации %s' % result['message'])
print('Количество оценок: %d' % result['nfev'])
solution = result['x']
evaluation = func(solution)
print('Решение: f(%s) = %.5f' % (solution, evaluation))
result

Статус оптимизации Optimization terminated successfully.
Количество оценок: 3
Решение: f([0. 0.]) = 0.00000


      fun: 0.0
 hess_inv: array([[ 0.75, -0.25],
       [-0.25,  0.75]])
      jac: array([0., 0.])
  message: 'Optimization terminated successfully.'
     nfev: 3
      nit: 2
     njev: 3
   status: 0
  success: True
        x: array([0., 0.])

Итак, мы получили, что минимум функции достигается в точке . Значение функции в этой точке также равно нулю.

Можно повторить то же самое с вариацией  L-BFGS-B:

In [8]:
# определяем нашу функцию
def func(x):
    return x[0]**2.0 + x[1]**2.0
 
#  определяем градиент функции
def grad_func(x):
    return np.array([x[0] * 2, x[1] * 2])
 
# определяем начальную точку
x_0 = [1, 1]
# реализуем алгоритм L-BFGS-B
result = minimize(func, x_0, method='L-BFGS-B', jac=grad_func)
# получаем результат
print('Статус оптимизации %s' % result['message'])
print('Количество оценок: %d' % result['nfev'])
solution = result['x']
evaluation = func(solution)
print('Решение: f(%s) = %.5f' % (solution, evaluation))
result

Статус оптимизации CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL
Количество оценок: 3
Решение: f([0. 0.]) = 0.00000


      fun: 0.0
 hess_inv: <2x2 LbfgsInvHessProduct with dtype=float64>
      jac: array([0., 0.])
  message: 'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
     nfev: 3
      nit: 2
     njev: 3
   status: 0
  success: True
        x: array([0., 0.])

Иногда количество итераций у двух модификаций различается, но ответ совпадает. Бывает также, что одна из вариаций может не сойтись, а другая — достичь экстремума, поэтому советуем не воспринимать их как взаимозаменяемые алгоритмы. На практике лучше пробовать разные варианты: если у вас не сошёлся алгоритм BFGS, можно попробовать L-BFGS-B, и наоборот. Также можно экспериментировать одновременно с обоими алгоритмами, чтобы выбрать тот, который будет сходиться для функции за меньшее число итераций и тем самым экономить время.

→ Важно понимать, что для некоторых функций не из всех стартовых точек получается достичь сходимости метода. Тогда их можно перебирать, к примеру, с помощью цикла.

✍ Итак, мы обсудили один из самых эффективных на сегодняшний день алгоритмов — вариацию BFGS квазиньютоновских методов. Вы будете регулярно сталкиваться с этим алгоритмом при решении различных задач и при использовании библиотек для оптимизации. Так что давайте попрактикуемся: в этом юните мы посмотрели фрагмент поэтапного разбора метода BFGS для функции
— давайте завершим начатое и найдём точку минимума ↓

 Задание 4.1

Найдите точку минимума для функции.

В качестве стартовой возьмите точку.

Значения координат округлите до целого числа.

In [9]:
# определяем нашу функцию
def func(x):
    return x[0]**2.0 - x[0]*x[1] + x[1]**2.0 + 9*x[0] - 6*x[1] + 20
 
#  определяем градиент функции
def grad_func(x):
    return np.array([2*x[0] - x[1] + 9, -x[0] + 2*x[1] - 6])
 
# определяем начальную точку
x_0 = [-400, -400]
# реализуем алгоритм L-BFGS-B
result = minimize(func, x_0, method='L-BFGS-B', jac=grad_func)
# получаем результат
print('Статус оптимизации %s' % result['message'])
print('Количество оценок: %d' % result['nfev'])
solution = result['x']
evaluation = func(solution)
print('Решение: f(%s) = %.0f' % (solution, evaluation))
result

Статус оптимизации CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL
Количество оценок: 9
Решение: f([-3.99999972  1.00000028]) = -1


      fun: -0.9999999999999218
 hess_inv: <2x2 LbfgsInvHessProduct with dtype=float64>
      jac: array([2.90029792e-07, 2.72413962e-07])
  message: 'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
     nfev: 9
      nit: 4
     njev: 9
   status: 0
  success: True
        x: array([-3.99999972,  1.00000028])

Задание 4.4

Найдите минимум функции

с помощью квазиньютоновского метода BFGS.

В качестве стартовой точки возьмите .

В качестве ответа введите минимальное значение функции в достигнутой точке.

In [10]:
# определяем нашу функцию
def func(x):
    return x**2 - 3*x + 45
 
#  определяем градиент функции
def grad_func(x):
    return 2*x - 3

x_0 = 10
# реализуем алгоритм BFGS
result = minimize(func, x_0, method='BFGS', jac=grad_func)
# получаем результат
print('Статус оптимизации %s' % result['message'])
print('Количество оценок: %d' % result['nfev'])
solution = result['x']
evaluation = func(solution)
print('Решение: f(%s) = %.0f' % (solution, evaluation))
result

Статус оптимизации Optimization terminated successfully.
Количество оценок: 5
Решение: f([1.5]) = 43


      fun: 42.75
 hess_inv: array([[0.5]])
      jac: array([0.])
  message: 'Optimization terminated successfully.'
     nfev: 5
      nit: 4
     njev: 5
   status: 0
  success: True
        x: array([1.5])

Задание 4.5

Решите предыдущую задачу, применяя модификацию L-BFGS-B.
В каком случае получилось меньше итераций?


In [11]:
# определяем нашу функцию
def func(x):
    return x**2 - 3*x + 45
 
#  определяем градиент функции
def grad_func(x):
    return 2*x - 3

x_0 = 10
# реализуем алгоритм L-BFGS-B
result = minimize(func, x_0, method='L-BFGS-B', jac=grad_func)
# получаем результат
print('Статус оптимизации %s' % result['message'])
print('Количество оценок: %d' % result['nfev'])
solution = result['x']
evaluation = func(solution)
print('Решение: f(%s) = %.0f' % (solution, evaluation))
result

Статус оптимизации CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL
Количество оценок: 3
Решение: f([1.5]) = 43


      fun: 42.75
 hess_inv: <1x1 LbfgsInvHessProduct with dtype=float64>
      jac: array([0.])
  message: 'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
     nfev: 3
      nit: 2
     njev: 3
   status: 0
  success: True
        x: array([1.5])

 Задание 4.7

Найдите минимум функции

, взяв за стартовую точку .
Какой алгоритм сошелся быстрее?


In [12]:
# определяем нашу функцию
def func(x):
    return x[0]**4 - 6*x[1]**2 + 10

#  определяем градиент функции
def grad_func(x):
    return np.array([4*x[0]**3, 12*x[1]])
 
# определяем начальную точку
x_0 = [100, 100]
# реализуем алгоритм L-BFGS-B
result = minimize(func, x_0, method='L-BFGS-B', jac=grad_func)
# получаем результат
print('Статус оптимизации %s' % result['message'])
print('Количество оценок: %d' % result['nfev'])
solution = result['x']
evaluation = func(solution)
print('Решение: f(%s) = %.0f' % (solution, evaluation))
result

Статус оптимизации ABNORMAL_TERMINATION_IN_LNSRCH
Количество оценок: 80
Решение: f([ 6.30130329 96.09299241]) = -53817


      fun: -53816.57909549914
 hess_inv: <2x2 LbfgsInvHessProduct with dtype=float64>
      jac: array([1000.80886128, 1153.11590889])
  message: 'ABNORMAL_TERMINATION_IN_LNSRCH'
     nfev: 80
      nit: 11
     njev: 80
   status: 2
  success: False
        x: array([ 6.30130329, 96.09299241])

In [13]:
# определяем нашу функцию
def func(x):
    return x[0]**4 - 6*x[1]**2 + 10

#  определяем градиент функции
def grad_func(x):
    return np.array([4*x[0]**3, 12*x[1]])
 
# определяем начальную точку
x_0 = [100, 100]
# реализуем алгоритм BFGS
result = minimize(func, x_0, method='BFGS', jac=grad_func)
# получаем результат
print('Статус оптимизации %s' % result['message'])
print('Количество оценок: %d' % result['nfev'])
solution = result['x']
evaluation = func(solution)
print('Решение: f(%s) = %.0f' % (solution, evaluation))
result

Статус оптимизации Optimization terminated successfully.
Количество оценок: 37
Решение: f([1.16598340e-02 1.25599922e-18]) = 10


      fun: 10.000000018482872
 hess_inv: array([[2.56856945e+02, 2.02286677e-11],
       [2.02286677e-11, 7.55805328e-02]])
      jac: array([6.34069831e-06, 1.50719906e-17])
  message: 'Optimization terminated successfully.'
     nfev: 37
      nit: 34
     njev: 37
   status: 0
  success: True
        x: array([1.16598340e-02, 1.25599922e-18])

## Пример № 1. SciPy (scipy.optimize.linprog)

У нас есть 6 товаров с заданными ценами на них и заданной массой.

Вместимость сумки, в которую мы можем положить товары, заранее известна и равна 15 кг.

Какой товар и в каком объёме необходимо взять, чтобы сумма всех цен товаров была максимальной?

Создадим переменные на основе предложенных данных:

In [14]:
import numpy as np

In [15]:
values = [4, 2, 1, 7, 3, 6] #стоимости товаров
weights = [5, 9, 8, 2, 6, 5] #вес товаров
C = 15 #вместимость сумки
n = 6 #количество товаров

Сформулируем задачу линейного программирования. Максимизируем произведение стоимости на количество, учитывая, что произведение веса на искомое количество товаров должно укладываться во вместимость сумки:

Из предыдущего юнита мы уже знаем, что в векторно-матричной форме наша задача должна формулироваться в следующем виде:

Получается, что в наших обозначениях мы имеем следующее:

Здесь нам необходимо вспомнить линейную алгебру, так как очень важно, чтобы векторы были в нужных нам размерностях, иначе мы не сможем использовать матричное умножение. Вектор размера мы превращаем в матрицу размера с помощью функции expand_dims(). Создаём все необходимые переменные:

In [16]:
c = - np.array(values) #изменяем знак, чтобы перейти от задачи максимизации к задаче минимизации
A = np.array(weights)  #конвертируем список с весами в массив
print(A)
A = np.expand_dims(A, 0) #преобразуем размерность массива
print(A)
b = np.array([C]) #конвертируем вместимость в массив

[5 9 8 2 6 5]
[[5 9 8 2 6 5]]


Передаём подготовленные переменные в оптимизатор SciPy:

In [17]:
from scipy.optimize import linprog
linprog(c=c, A_ub=A, b_ub=b)

           con: array([], dtype=float64)
 crossover_nit: 0
         eqlin:  marginals: array([], dtype=float64)
  residual: array([], dtype=float64)
           fun: -52.5
       ineqlin:  marginals: array([-3.5])
  residual: array([0.])
         lower:  marginals: array([13.5, 29.5, 27. ,  0. , 18. , 11.5])
  residual: array([0. , 0. , 0. , 7.5, 0. , 0. ])
       message: 'Optimization terminated successfully. (HiGHS Status 7: Optimal)'
           nit: 0
         slack: array([0.])
        status: 0
       success: True
         upper:  marginals: array([0., 0., 0., 0., 0., 0.])
  residual: array([inf, inf, inf, inf, inf, inf])
             x: array([0. , 0. , 0. , 7.5, 0. , 0. ])

Получаем искомое значение функции —  (в выводе значение с минусом, но мы меняем знак, возвращаясь к задаче максимизации). . Таким образом, мы взяли только самую дорогую, четвёртую вещь. Она одна весит 2 кг, а если взять её 7.5 раз, то получится как раз 15 кг. Отлично, задача решена.

## Пример № 2. CVXPY

Снова решим задачу из примера № 1, но уже предположим, что товары нельзя дробить, и будем решать задачу целочисленного линейного программирования.

SciPy не умеет решать такие задачи, поэтому будем использовать новую библиотеку CVXPY.

Важно! С установкой этот библиотеки порой возникают проблемы. Если вы столкнулись с трудностями, посоветуйтесь с ментором или воспользуйтесь Google Colaboratory.

In [18]:
!pip install cvxpy

Defaulting to user installation because normal site-packages is not writeable


In [19]:
import cvxpy

С помощью CVXPY создадим переменную-массив. Укажем его размерность, а также условие, что все числа в массиве должны быть целыми:

In [20]:
x = cvxpy.Variable(shape=n, integer = True)

Далее зададим ограничения, используя матричное умножение:

In [21]:
A = A.flatten() # Преобразуем размерность массива
constraint = cvxpy.sum(cvxpy.multiply(A, x)) <= C
x_positive = x >= 0
total_value = cvxpy.sum(cvxpy.multiply(x, c))

Переходим непосредственно к решению задачи:

In [22]:
problem = cvxpy.Problem(cvxpy.Minimize(total_value), constraints=[constraint, x_positive])

Вызываем получившееся решение:

In [23]:
problem.solve()

-49.0

Здесь мы уже получаем , и берём только четвёртый товар в количестве семи штук. Можно увидеть, что результат, в целом, очень близок к первому, когда мы использовали библиотеку SciPy — различие лишь в добавлении целочисленности. Значит, у нас получилось решить задачу, когда мы добавили недостающее условие.

In [24]:
x.value

array([-0., -0., -0.,  7., -0.,  0.])

А что если мы можем брать не любое количество товаров, а только один или не брать их вовсе? Задаём  типа boolean.

In [25]:
x = cvxpy.Variable(shape=n, boolean=True)
constraint = cvxpy.sum(cvxpy.multiply(A, x)) <= C
x_positive = x >= 0
total_value = cvxpy.sum(cvxpy.multiply(x, c))

problem = cvxpy.Problem(
    cvxpy.Minimize(total_value), constraints=[constraint, x_positive]
)

problem.solve()
x.value

array([1., 0., 0., 1., 0., 1.])

Получим стоимость, равную , взяв первый, четвёртый и шестой товары.

Обратите внимание, что, используя SciPy, мы могли не указывать явно, что только положительные, так как в линейном программировании считаются только неотрицательные .

А вот CVXPY универсальна. Мы просто задали функцию, не указывая, что это линейное программирование. CVXPY «поняла», что это задача оптимизации, и использовала нужные алгоритмы. Поэтому здесь ограничение на положительные  мы указывали явно.


## Пример № 3. PuLP

В нашей каршеринговой компании две модели автомобилей: модель и модель . Автомобиль даёт прибыль в размере 20 тысяч в месяц, а автомобиль — 45 тысяч в месяц. Мы хотим заказать на заводе новые автомобили и максимизировать прибыль. Однако на производство и ввод в эксплуатацию автомобилей понадобится время:

        Проектировщику требуется 4 дня, чтобы подготовить документы для производства каждого автомобиля типа , и 5 дней — для каждого автомобиля типа .
        Заводу требуется 3 дня, чтобы изготовить модель , и 6 дней, чтобы изготовить модель .
        Менеджеру требуется 2 дня, чтобы ввести в эксплуатацию в компании автомобиль , и 7 дней —  автомобиль .
        Каждый специалист может работать суммарно 30 дней.


In [26]:
!pip install pulp

Defaulting to user installation because normal site-packages is not writeable
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.3/14.3 MB 6.9 MB/s eta 0:00:0000:0100:01


In [29]:
import pulp
from pulp import *

Заметьте, что здесь мы снова пишем обычные неравенства, а не условия в матричном виде. Дело в том, что для данной библиотеки так «удобнее», так как она принимает все условия в «первичном» виде.


In [30]:
problem = LpProblem('Производство машин', LpMaximize)
A = LpVariable('Автомобиль A', lowBound=0 , cat=LpInteger)
B = LpVariable('Автомобиль B', lowBound=0 , cat=LpInteger)
#Целевая функция
problem += 20000*A + 45000*B 
#Ограничения
problem += 4*A + 5*B <= 30 
problem += 3*A + 6*B <=30
problem += 2*A + 7*B <=30
problem.solve()
print("Количество автомобилей модели А: ", A.varValue)
print("Количество автомобилей модели В: ", B.varValue)
print("Суммарный доход: ", value(problem.objective))

Welcome to the CBC MILP Solver 
Version: 2.10.3 
Build Date: Dec 15 2019 

command line - /home/egor/.local/lib/python3.10/site-packages/pulp/solverdir/cbc/linux/64/cbc /tmp/c9e566e9c1ea418dbb548dda2820e172-pulp.mps max timeMode elapsed branch printingOptions all solution /tmp/c9e566e9c1ea418dbb548dda2820e172-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 8 COLUMNS
At line 21 RHS
At line 25 BOUNDS
At line 28 ENDATA
Problem MODEL has 3 rows, 2 columns and 6 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Continuous objective value is 216667 - 0.00 seconds
Cgl0004I processed model has 3 rows, 2 columns (2 integer (0 of which binary)) and 6 elements
Cutoff increment increased from 1e-05 to 5000
Cbc0012I Integer solution of -195000 found by DiveCoefficient after 0 iterations and 0 nodes (0.00 seconds)
Cbc0012I Integer solution of -200000 found by DiveCoefficient after 1 iterations and 0 nodes (0.00 seconds)
Cbc

/home/egor/.local/lib/python3.10/site-packages/pulp/pulp.py:1352: UserWarning: Spaces are not permitted in the name. Converted to '_'
  warnings.warn("Spaces are not permitted in the name. Converted to '_'")


Выходит, что необходимо произвести 1 автомобиль типа и 4 автомобиля типа . Тогда суммарный чистый доход будет равен 200 тысячам.

Задание 6.1

Составьте оптимальный план перевозок со склада № 1 и склада № 2 в три торговых центра с учётом тарифов, запасов на складах и потребностей торговых центров, которые указаны в таблице:

Сформулируйте предложенную задачу как задачу линейного программирования и решите её любым способом (желательно программным).

В качестве ответа введите минимальную суммарную стоимость поставки. Ответ округлите до целого числа.

In [33]:
problem = LpProblem('Доставка со склада', LpMinimize)
A = LpVariable('ТЦ1', lowBound=0 , cat=LpInteger)
B = LpVariable('ТЦ2', lowBound=0 , cat=LpInteger)
C = LpVariable('ТЦ3', lowBound=0 , cat=LpInteger)
D = LpVariable('ТЦ1', lowBound=0 , cat=LpInteger)
E = LpVariable('ТЦ2', lowBound=0 , cat=LpInteger)
F = LpVariable('ТЦ3', lowBound=0 , cat=LpInteger)
#Целевая функция
problem += 2*A + 5*B + 3*C
problem += 7*D + 7*E + 6*F
#Ограничения
problem += A + B + C <= 180 
problem += D + E + F <= 220
problem += A + D <= 110
problem += B + E <= 150
problem += C + F <= 140
problem.solve()
print("Количество отгрузок на склад A: ", A.varValue)
print("Количество отгрузок на склад B: ", B.varValue)
print("Количество отгрузок на склад C: ", C.varValue)
print("Количество отгрузок на склад D: ", D.varValue)
print("Количество отгрузок на склад E: ", E.varValue)
print("Количество отгрузок на склад F: ", F.varValue)
print("Суммарный доход: ", value(problem.objective))

/home/egor/.local/lib/python3.10/site-packages/pulp/pulp.py:1352: UserWarning: Spaces are not permitted in the name. Converted to '_'
  warnings.warn("Spaces are not permitted in the name. Converted to '_'")
/home/egor/.local/lib/python3.10/site-packages/pulp/pulp.py:1704: UserWarning: Overwriting previously set objective.
  warnings.warn("Overwriting previously set objective.")


Welcome to the CBC MILP Solver 
Version: 2.10.3 
Build Date: Dec 15 2019 

command line - /home/egor/.local/lib/python3.10/site-packages/pulp/solverdir/cbc/linux/64/cbc /tmp/0bb1986eba5143ae851b9b7c7a49290a-pulp.mps timeMode elapsed branch printingOptions all solution /tmp/0bb1986eba5143ae851b9b7c7a49290a-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 10 COLUMNS
Duplicate row C0000000 at line 17 <     X0000001  C0000000   1.000000000000e+00 >
Duplicate row C0000001 at line 18 <     X0000001  C0000001   1.000000000000e+00 >
Duplicate row C0000002 at line 19 <     X0000001  C0000002   1.000000000000e+00 >
Duplicate row C0000000 at line 28 <     X0000003  C0000000   1.000000000000e+00 >
Duplicate row C0000001 at line 29 <     X0000003  C0000001   1.000000000000e+00 >
Duplicate row C0000003 at line 30 <     X0000003  C0000003   1.000000000000e+00 >
Duplicate row C0000000 at line 39 <     X0000005  C0000000   1.000000000000e+00 >
Duplicate row C0000001 at

PulpSolverError: Pulp: Error while executing /home/egor/.local/lib/python3.10/site-packages/pulp/solverdir/cbc/linux/64/cbc